### ISSUE TITLE
.env file Authorization: Token token format?

### ISSUE THREAD

**Issue by rijotech** [emilyjimenez/Jeffreys-GreenbitsAPI-Project#26]
What is the format i should use inside the .env file?
this is what i have but it doesn't work.

Authorization: Token token="{6qKnraM-b8IVzU6XrAqLeB}"
X-GB-CompanyId: {32121}

not an actual token or company ID.

Also there is a 404 on localhost/build/js/app.js?LivePage=15203984493 404 {not found}  meaning the app.js is not there.

**Comment by emilyjimenez** [comment]
Hi Rijo, 

Because the company I built this for only has one location I did not include the company ID. My .env file looks like this:

exports.authorizationToken = "Token token=<YOUR_TOKEN_HERE>";

^No brackets or curly braces needed.

You'd need to make quite a few changes if you're building a menu for multiple locations but the company ID would also go in the .env file and you'd edit the API url in the lookup.js file.

Did you follow this installation instructions in the README? After cloning, in the your teminal run 'npm install', 'bower install', 'gulp build', and 'gulp serve'. Also I would check the package.json to make sure you have the right versions of all dependencies installed.

So happy people are actually interested in this! Let me know if you have any more questions. :)

**Comment by rijotech** [comment]
I see, I'm just testing what you did with a store token and company's ID. I'll give a try one more time, thanks. 
And yes you're right about the dependencies i think i may need a mac since some of the jnode dependency are only available on mac

**Comment by emilyjimenez** [comment]
Ooo yeah sorry, I'm a mac user. I don't know if it applies here but I've used [Yarn](https://yarnpkg.com/en/) when I have dependency issues on other projects, might be something to check out.

The [API documentation](https://developer.greenbits.com/v1/) states without the company ID in the header, the API responses will automatically constrain to the token owner’s first accessible location.  

Also to be clear, it's not a store token, it's an authorization token. You get the auth token by running a get request to https://api.greenbits.com/api/v1/me with your username and password.

Hope that helps, happy coding!
